### ISSUE TITLE
Crash on windows 10 when build with release mode.

### ISSUE THREAD

**Issue by halx99** [rwfpl/rewolf-wow64ext#10]
When I use any 64 API to operate a 64bits application, the follow exception occrued, but if I press 'continue' again and again, The result seems ok.
![default](https://cloud.githubusercontent.com/assets/6977319/21971387/18f048d6-dbeb-11e6-88f0-5c9f6cffb751.png)

![default](https://cloud.githubusercontent.com/assets/6977319/21971448/adf6e7dc-dbeb-11e6-8437-d8edd53b09f5.png)

Exception thrown at 0x5A180094 in x-studio365.core.dll: 0xC0000005: Access violation writing location 0x08C0A5D8.

Unhandled exception at 0x5A180094 in x-studio365.core.dll: 0xC0000005: Access violation writing location 0x08C0A5D8.

Exception thrown at 0x7703361D (ntdll.dll) in x-studio365.core.dll: 0xC0000005: Access violation reading location 0x00000018.

Unhandled exception at 0x7703361D (ntdll.dll) in x-studio365.core.dll: 0xC0000005: Access violation reading location 0x00000018.

The thread 0x2da8 has exited with code 0 (0x0).
The thread 0x3da8 has exited with code 0 (0x0).
Exception thrown at 0x5A180094 in x-studio365.core.dll: 0xC0000005: Access violation writing location 0x08C0A618.

Unhandled exception at 0x5A180094 in x-studio365.core.dll: 0xC0000005: Access violation writing location 0x08C0A618.

Exception thrown at 0x770403A0 (ntdll.dll) in x-studio365.core.dll: 0xC0000005: Access violation reading location 0x00000030.

Unhandled exception at 0x770403A0 (ntdll.dll) in x-studio365.core.dll: 0xC0000005: Access violation reading location 0x00000030.

Exception thrown at 0x5A180094 in x-studio365.core.dll: 0xC0000005: Access violation writing location 0x08C0A5E8.

Unhandled exception at 0x5A180094 in x-studio365.core.dll: 0xC0000005: Access violation writing location 0x08C0A5E8.

Exception thrown at 0x77048F36 (ntdll.dll) in x-studio365.core.dll: 0xC0000005: Access violation reading location 0x00000030.

Exception thrown at 0x77048F36 (ntdll.dll) in x-studio365.core.dll: 0xC0000005: Access violation reading location 0x00000030.

Unhandled exception at 0x77048F36 (ntdll.dll) in x-studio365.core.dll: 0xC0000005: Access violation reading location 0x00000030.

**Comment by rwfpl** [comment]
Can you share snippet of code that causes this issue?

**Comment by halx99** [comment]
Here is the test project: 
[rewolf-wow64ext-crash.zip](https://github.com/rwfpl/rewolf-wow64ext/files/707615/rewolf-wow64ext-crash.zip)

By the way, My Windows version is: 10.0.15007.1000

**Comment by rwfpl** [comment]
Ah, I guess new win10 build had to break something. I'll take a closer look then, thanks for reporting!

**Comment by halx99** [comment]
Thanks, looking forward your response

**Comment by rwfpl** [comment]
The current wow64ext code interferes with the Return Flow Guard (RFG) mitigation, I'm checking if it can be easily fixed, stay tuned.

**Comment by rwfpl** [comment]
Fixed https://github.com/rwfpl/rewolf-wow64ext/commit/fd28b57fe926f3e57540850c37cdbcc766173dba

**Comment by halx99** [comment]
Wow, great job, thanks, let me try immediately.

**Comment by halx99** [comment]
This project is very useful for me to develop the Unity64bit Lua Project Debug tool, thanks again for you bring this excellent Project.
