### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by eclessiastes** [rwfpl/rewolf-wow64ext#8]
There is a lot of errors:
Error 3 error C3861: ‘offsetof’: identifier not found C:\Users\home\Desktop\rewolf-wow64ext-master\rewolf-wow64ext-master\src\wow64ext.cpp 300 1 wow64ext
Error 2 error C2065: ‘InLoadOrderModuleList’ : undeclared identifier C:\Users\home\Desktop\rewolf-wow64ext-master\rewolf-wow64ext-master\src\wow64ext.cpp 300 1 wow64ext
Error 1 error C2275: ‘PEB_LDR_DATA64’ : illegal use of this type as an expression C:\Users\home\Desktop\rewolf-wow64ext-master\rewolf-wow64ext-master\src\wow64ext.cpp 300 1 wow64ext
How can i solve this ?

**Comment by hannescmarits** [comment]
For VS 13 adding #include "stddef.h"  to wow64ext.cpp solves the problem.
